### PR TITLE
Fix  #239 merge conflict

### PR DESCRIPTION
**Pull request by darosior**
There was a silent merge conflict in  #239, which i merged without testing it. This fixes the compilation errors.

### CODE REVIEW

**Comment by darosior** [comment]
utACK db70a2dc9ccff930efa523234689dd0dc5c274a5
